---
- include:              '../tasks/user_groups.yml'
  vars:
    user_groups:
      - "{{ backup_user }}-at-{{ backup_client }}"
  with_items:           "{{ hostvars[backup_client]['backup_users'] }}"
  loop_control:
    loop_var:           backup_user

- include:              '../tasks/users.yml'
  vars:
    users:
      - "{{ backup_user }}-at-{{ backup_client }}"
  with_items:           "{{ hostvars[backup_client]['backup_users'] }}"
  loop_control:
    loop_var:           backup_user

- include:              '../tasks/authorized_keys.yml'
  vars:
    authorized_keys:
      - user:             "{{ backup_user }}-at-{{ backup_client }}"
        keyfile:          "{{ role_path }}/../../inventory/hosts/{{ backup_client }}/users/{{ backup_user }}/files/ssh_keys/id_rsa.pub"
  with_items:           "{{ hostvars[backup_client]['backup_users'] }}"
  loop_control:
    loop_var:           backup_user

- include:              '../tasks/allow_users.yml'
  vars:
    allow_users:
      - "{{ backup_user }}-at-{{ backup_client }}"
  with_items:           "{{ hostvars[backup_client]['backup_users'] }}"
  loop_control:
    loop_var:           backup_user
